/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2024-08-19 02:15:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./view/Footer.jsp", Long.valueOf(1724033746959L));
    _jspx_dependants.put("/./view/Header.jsp", Long.valueOf(1723613442632L));
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\t\r\n");
	
request.setCharacterEncoding("UTF-8");	
String cp = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/custom-font.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    .btn-arrow-left {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .mdl-layout__content{\r\n");
      out.write("\tmargin: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".demo-card-wide.mdl-card {\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write(".demo-card-wide > .mdl-card__title {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("  height: 176px;\r\n");
      out.write("  background: url('images/1.jpg') center / cover;\r\n");
      out.write("}\r\n");
      out.write(".demo-card-wide > .mdl-card__menu {\r\n");
      out.write("  color: #fff;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	String userID = null;
	if (session.getAttribute("userID") != null) {
		userID = (String) session.getAttribute("userID");
	}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".btn-arrow-left {\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mdl-layout mdl-js-layout\">\r\n");
      out.write("\t\t<header class=\"mdl-layout__header mdl-layout__header--scroll\">\r\n");
      out.write("\t\t\t<div class=\"mdl-layout__header-row\">\r\n");
      out.write("\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\"><span class=\"mdl-layout-title\" >JSP 게시판 웹 사이트</span></a>\r\n");
      out.write("\t\t\t\t<!-- Add spacer, to align navigation to the right -->\r\n");
      out.write("\t\t\t\t<div class=\"mdl-layout-spacer\"></div>\r\n");
      out.write("\t\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t\t<nav class=\"mdl-navigation\">\r\n");
      out.write("\t\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\">메인</a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-navigation__link\" href=\"BBS.do\">게시판</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"mdl-layout__drawer\">\r\n");
      out.write("\t\t\t<span class=\"mdl-layout-title\">Title</span>\r\n");
      out.write("\t\t\t<nav class=\"mdl-navigation\">\r\n");
      out.write("\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\">메인</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"mdl-navigation__link\" href=\"BBS.do\">게시판</a>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("  <main class=\"mdl-layout__content\">\r\n");
      out.write("<div class=\"demo-card-wide mdl-card mdl-shadow--2dp\">\r\n");
      out.write("  <div class=\"mdl-card__title\">\r\n");
      out.write("    <h2 class=\"mdl-card__title-text\">JSP 게시판 웹 사이트</h2>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mdl-card__supporting-text\">\r\n");
      out.write(" \tStruts, MDL, JSP 사용\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mdl-card__actions mdl-card--border\">\r\n");
      out.write("    <button  onclick=\"location.href='BBS.do'\" class=\"mdl-button mdl-js-button mdl-button--raised mdl-button--colored\">\r\n");
      out.write("      바로 글쓰러 가기\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"mdl-card__menu\">\r\n");
      out.write("    <button class=\"mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect\">\r\n");
      out.write("      <i class=\"material-icons\">share</i>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("  </main>\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    .btn-arrow-left {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"mdl-mini-footer\">\r\n");
      out.write("  <div class=\"mdl-mini-footer__left-section\">\r\n");
      out.write("    <div class=\"mdl-logo\">Title</div>\r\n");
      out.write("    <ul class=\"mdl-mini-footer__link-list\">\r\n");
      out.write("      <li><a href=\"#\">Help</a></li>\r\n");
      out.write("      <li><a href=\"#\">Privacy & Terms</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
