/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2024-08-19 02:27:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;
import bbs.BbsDAO;
import bbs.BbsForm;
import java.util.ArrayList;

public final class BBSSearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/Header.jsp", Long.valueOf(1723613442632L));
    _jspx_dependants.put("/view/Footer.jsp", Long.valueOf(1724033746959L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
String cp = request.getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#bbs-table {\r\n");
      out.write("\tbox-shadow: 4px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbs-table th, #bbs-table td {\r\n");
      out.write("\tvertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-container {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center; /* Center align buttons */\r\n");
      out.write("\tmargin-bottom: 20px; /* Add bottom margin for spacing */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination-container {\r\n");
      out.write("\tmargin-top: 20px; /* Add top margin for spacing */\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center; /* Center align pagination */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination-container a {\r\n");
      out.write("\tcolor: #007bff; /* Bootstrap primary link color */\r\n");
      out.write("\tpadding: 6px 12px;\r\n");
      out.write("\tmargin: 0 4px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tborder: 1px solid #007bff; /* Bootstrap primary border color */\r\n");
      out.write("\tborder-radius: 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".pagination-container .active a {\r\n");
      out.write("\tbackground-color: #007bff; /* Bootstrap primary background color */\r\n");
      out.write("\tcolor: #fff; /* White text for active link */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mdl-layout__content{\r\n");
      out.write("\tmargin: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-inline{\r\n");
      out.write("\tgap: 8px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	ArrayList<BbsForm> list = new ArrayList<BbsForm>();
	
	String userID = null;
	BbsDAO bbsDAO = new BbsDAO();
	if (session.getAttribute("userID") != null) {
		userID = (String) session.getAttribute("userID");
	}

	int pageNumber = 1;
	if (request.getParameter("pageNumber") != null) {
		pageNumber = Integer.parseInt(request.getParameter("pageNumber"));
	}

	String category = null;
	if (request.getParameter("category") != null) {
		category = request.getParameter("category");
	}
	String bbsCategory = null;
	if (request.getParameter("bbsCategory") != null) {
		bbsCategory = request.getParameter("bbsCategory");
	}

	String searchKeyword = null;
	if (request.getParameter("searchKeyword") != null) {
		searchKeyword = request.getParameter("searchKeyword");
		list = bbsDAO.search(bbsCategory, searchKeyword);
	}

	
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("function searchIt(event){\r\n");
      out.write("    event.preventDefault();  // 기본 폼 제출 동작 방지\r\n");
      out.write("\r\n");
      out.write("    console.log(\"searchIt 호출\");\r\n");
      out.write("\r\n");
      out.write("    var f = document.myForm;\r\n");
      out.write("\r\n");
      out.write("    var str = f.searchKeyword.value.trim();\r\n");
      out.write("    f.searchKeyword.value = str;\r\n");
      out.write("\r\n");
      out.write("    str = f.bbsCategory.value.trim();\r\n");
      out.write("    f.bbsCategory.value = str;\r\n");
      out.write("  // Check if action is correctly set\r\n");
      out.write("    console.log(\"Action URL: \" + f.action);\r\n");
      out.write("\r\n");
      out.write("    f.action = \"./search_ok.do\";  // Ensure the URL is correct\r\n");
      out.write("    f.method = \"post\";  // Set form method to POST\r\n");
      out.write("    f.submit();\r\n");
      out.write("    console.log(\"성공적으로 검색 데이터 전송\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".btn-arrow-left {\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mdl-layout mdl-js-layout\">\r\n");
      out.write("\t\t<header class=\"mdl-layout__header mdl-layout__header--scroll\">\r\n");
      out.write("\t\t\t<div class=\"mdl-layout__header-row\">\r\n");
      out.write("\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\"><span class=\"mdl-layout-title\" >JSP 게시판 웹 사이트</span></a>\r\n");
      out.write("\t\t\t\t<!-- Add spacer, to align navigation to the right -->\r\n");
      out.write("\t\t\t\t<div class=\"mdl-layout-spacer\"></div>\r\n");
      out.write("\t\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t\t<nav class=\"mdl-navigation\">\r\n");
      out.write("\t\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\">메인</a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-navigation__link\" href=\"BBS.do\">게시판</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"mdl-layout__drawer\">\r\n");
      out.write("\t\t\t<span class=\"mdl-layout-title\">Title</span>\r\n");
      out.write("\t\t\t<nav class=\"mdl-navigation\">\r\n");
      out.write("\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\">메인</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"mdl-navigation__link\" href=\"BBS.do\">게시판</a>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container mt-4\">\r\n");
      out.write("    <div class=\"row justify-content-end mb-2\">\r\n");
      out.write("        <div class=\"col-auto\">\r\n");
      out.write("            <form class=\"form-inline\" method=\"post\" action=\"\" name=\"myForm\">\r\n");
      out.write("                <select name=\"bbsCategory\" id=\"bbsCategory\" class=\"form-control\">\r\n");
      out.write("                    <option value=\"bbsTitle\">제목</option>\r\n");
      out.write("                    <option value=\"bbsId\">게시물 번호</option>\r\n");
      out.write("                </select>\r\n");
      out.write("                <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"검색어 입력\" aria-label=\"Search\" name=\"searchKeyword\">\r\n");
      out.write("                <button class=\"btn btn-outline-primary my-2 my-sm-0\" onclick=\"searchIt(event)\">검색</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <table class=\"table table-striped\" id=\"bbs-table\">\r\n");
      out.write("            <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th scope=\"col\" style=\"width: 15%\">No.</th>\r\n");
      out.write("                    <th scope=\"col\" style=\"width: 15%\">종류</th>\r\n");
      out.write("                    <th scope=\"col\" style=\"width: 30%\">제목</th>\r\n");
      out.write("                    <th scope=\"col\" style=\"width: 20%\">작성일</th>\r\n");
      out.write("                    <th scope=\"col\">조회수</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f1_reused = false;
      try {
        _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f1.setParent(null);
        // /view/BBSSearch.jsp(148,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setVar("listCount");
        // /view/BBSSearch.jsp(148,16) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f1.setValue(bbsDAO.getNextPage(category));
        int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
        if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
        _jspx_th_c_005fset_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
      }
      out.write("\r\n");
      out.write("                ");

                for (int i = 0; i < list.size(); i++) {
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td>");
      out.print(list.get(i).getBbsId());
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(list.get(i).getBbsCategory());
      out.write("</td>\r\n");
      out.write("                    <td><a href=\"view.do?bbsID=");
      out.print(list.get(i).getBbsId());
      out.write('"');
      out.write('>');
      out.print(list.get(i).getBbsTitle());
      out.write("</a></td>\r\n");
      out.write("                    <td>");
      out.print(list.get(i).getBbsDate().substring(0, 16).replace(" ", "<br>"));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(list.get(i).getBbsView());
      out.write("</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                }
                
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("       \r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    .btn-arrow-left {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<footer class=\"mdl-mini-footer\">\r\n");
      out.write("  <div class=\"mdl-mini-footer__left-section\">\r\n");
      out.write("    <div class=\"mdl-logo\">Title</div>\r\n");
      out.write("    <ul class=\"mdl-mini-footer__link-list\">\r\n");
      out.write("      <li><a href=\"#\">Help</a></li>\r\n");
      out.write("      <li><a href=\"#\">Privacy & Terms</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /view/BBSSearch.jsp(147,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("BbsCategory");
      // /view/BBSSearch.jsp(147,16) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/view/BBSSearch.jsp(147,16) 'null'",_jsp_getExpressionFactory().createValueExpression("null",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
