/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.99
 * Generated at: 2024-08-19 00:19:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/Header.jsp", Long.valueOf(1723613442632L));
    _jspx_dependants.put("/view/Footer.jsp", Long.valueOf(1723613550616L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String cp = request.getContextPath();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>jsp 게시판 웹 사이트</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#bbs-table {\r\n");
      out.write("    box-shadow: 4px 4px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbs-table td {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbs-table td input {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbs-table td option {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    text-align: left;\r\n");
      out.write("    width:100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#bbs-table th {\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    background-color: #eeeeee; \r\n");
      out.write("    text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mdl-layout__content{\r\n");
      out.write("\tmargin: 40px;\r\n");
      out.write("}\r\n");
      out.write(".mdl-grid {\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input.form-control, textarea.form-control {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tbox-sizing: border-box; /* padding 및 border를 포함하여 너비를 계산 */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("textarea.form-control {\r\n");
      out.write("\tresize: vertical; /* 세로로만 크기 조절 가능하도록 설정 */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tfunction sendIt(event) {\r\n");
      out.write("\t\t\tconsole.log(\"쓰기 호출\");\r\n");
      out.write("\t\t\tevent.preventDefault(); // 기본 폼 제출 동작 방지\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar f = document.myForm;\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar str = f.bbsTitle.value.trim();\r\n");
      out.write("\t\t\tif (!str) {\r\n");
      out.write("\t\t\t\talert(\"\\n제목을 입력하세요.\");\r\n");
      out.write("\t\t\t\tf.bbsTitle.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.bbsTitle.value = str;\r\n");
      out.write("\r\n");
      out.write("\t\t\tstr = f.bbsContent.value.trim();\r\n");
      out.write("\t\t\tif (!str) {\r\n");
      out.write("\t\t\t\talert(\"\\n내용을 입력하세요.\");\r\n");
      out.write("\t\t\t\tf.bbsContent.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.bbsContent.value = str;\r\n");
      out.write("\r\n");
      out.write("\t\t\tstr = f.bbsCategory.value.trim();\r\n");
      out.write("\t\t\tif (!str) {\r\n");
      out.write("\t\t\t\talert(\"\\n카테고리를 선택하세요.\");\r\n");
      out.write("\t\t\t\tf.bbsCategory.focus();\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tf.bbsCategory.value = str;\r\n");
      out.write("\r\n");
      out.write("\t\t\t// URL 확인\r\n");
      out.write("\t\t\tconsole.log(\"Action URL: \" + f.action);\r\n");
      out.write("\r\n");
      out.write("\t\t\tf.action = \"./write_ok.do\";\r\n");
      out.write("\t\t\tf.submit();\r\n");
      out.write("\t\t\tconsole.log(\"성공적으로 전송\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".btn-arrow-left {\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"mdl-layout mdl-js-layout\">\r\n");
      out.write("\t\t<header class=\"mdl-layout__header mdl-layout__header--scroll\">\r\n");
      out.write("\t\t\t<div class=\"mdl-layout__header-row\">\r\n");
      out.write("\t\t\t\t<!-- Title -->\r\n");
      out.write("\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\"><span class=\"mdl-layout-title\" >JSP 게시판 웹 사이트</span></a>\r\n");
      out.write("\t\t\t\t<!-- Add spacer, to align navigation to the right -->\r\n");
      out.write("\t\t\t\t<div class=\"mdl-layout-spacer\"></div>\r\n");
      out.write("\t\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t\t<nav class=\"mdl-navigation\">\r\n");
      out.write("\t\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\">메인</a> <a\r\n");
      out.write("\t\t\t\t\t\tclass=\"mdl-navigation__link\" href=\"BBS.do\">게시판</a>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<div class=\"mdl-layout__drawer\">\r\n");
      out.write("\t\t\t<span class=\"mdl-layout-title\">Title</span>\r\n");
      out.write("\t\t\t<nav class=\"mdl-navigation\">\r\n");
      out.write("\t\t\t\t<a class=\"mdl-navigation__link\" href=\"main.do\">메인</a> <a\r\n");
      out.write("\t\t\t\t\tclass=\"mdl-navigation__link\" href=\"BBS.do\">게시판</a>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<main class=\"mdl-layout__content\">\r\n");
      out.write("\t\t\t<div class=\"page-content\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<form method=\"post\" name=\"myForm\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"mdl-data-table mdl-js-data-table\" id=\"bbs-table\" style=\"border: 1px solid #dddddd;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th class=\"mdl-data-table__cell--non-numeric\" colspan=\"2\">게시판 글쓰기 양식</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><select name=\"bbsCategory\" id=\"bbsCategory\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"notice\">공지</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"free\">자유</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"question\">질문</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"text\" class=\"form-control\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tplaceholder=\"글 제목\" name=\"bbsTitle\" maxlength=\"50\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td colspan=\"2\"><textarea \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"글 내용\" name=\"bbsContent\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tmaxlength=\"2048\" style=\"height: 350px;\"></textarea></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t<button\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"mdl-button mdl-js-button mdl-button--raised mdl-button--colored\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"sendIt(event)\">글쓰기</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</main>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t ");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/icon?family=Material+Icons\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://code.getmdl.io/1.3.0/material.indigo-pink.min.css\">\r\n");
      out.write("<script defer src=\"https://code.getmdl.io/1.3.0/material.min.js\"></script>\r\n");
      out.write("<title>JSP 게시판 웹 사이트</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("    .btn-arrow-left {\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"mdl-mega-footer\">\r\n");
      out.write("  <div class=\"mdl-mega-footer__middle-section\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mdl-mega-footer__drop-down-section\">\r\n");
      out.write("      <input class=\"mdl-mega-footer__heading-checkbox\" type=\"checkbox\" checked>\r\n");
      out.write("      <h1 class=\"mdl-mega-footer__heading\">Features</h1>\r\n");
      out.write("      <ul class=\"mdl-mega-footer__link-list\">\r\n");
      out.write("        <li><a href=\"#\">About</a></li>\r\n");
      out.write("        <li><a href=\"#\">Terms</a></li>\r\n");
      out.write("        <li><a href=\"#\">Partners</a></li>\r\n");
      out.write("        <li><a href=\"#\">Updates</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mdl-mega-footer__drop-down-section\">\r\n");
      out.write("      <input class=\"mdl-mega-footer__heading-checkbox\" type=\"checkbox\" checked>\r\n");
      out.write("      <h1 class=\"mdl-mega-footer__heading\">Details</h1>\r\n");
      out.write("      <ul class=\"mdl-mega-footer__link-list\">\r\n");
      out.write("        <li><a href=\"#\">Specs</a></li>\r\n");
      out.write("        <li><a href=\"#\">Tools</a></li>\r\n");
      out.write("        <li><a href=\"#\">Resources</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mdl-mega-footer__drop-down-section\">\r\n");
      out.write("      <input class=\"mdl-mega-footer__heading-checkbox\" type=\"checkbox\" checked>\r\n");
      out.write("      <h1 class=\"mdl-mega-footer__heading\">Technology</h1>\r\n");
      out.write("      <ul class=\"mdl-mega-footer__link-list\">\r\n");
      out.write("        <li><a href=\"#\">How it works</a></li>\r\n");
      out.write("        <li><a href=\"#\">Patterns</a></li>\r\n");
      out.write("        <li><a href=\"#\">Usage</a></li>\r\n");
      out.write("        <li><a href=\"#\">Products</a></li>\r\n");
      out.write("        <li><a href=\"#\">Contracts</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mdl-mega-footer__drop-down-section\">\r\n");
      out.write("      <input class=\"mdl-mega-footer__heading-checkbox\" type=\"checkbox\" checked>\r\n");
      out.write("      <h1 class=\"mdl-mega-footer__heading\">FAQ</h1>\r\n");
      out.write("      <ul class=\"mdl-mega-footer__link-list\">\r\n");
      out.write("        <li><a href=\"#\">Questions</a></li>\r\n");
      out.write("        <li><a href=\"#\">Answers</a></li>\r\n");
      out.write("        <li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"mdl-mega-footer__bottom-section\">\r\n");
      out.write("    <div class=\"mdl-logo\">Title</div>\r\n");
      out.write("    <ul class=\"mdl-mega-footer__link-list\">\r\n");
      out.write("      <li><a href=\"#\">Help</a></li>\r\n");
      out.write("      <li><a href=\"#\">Privacy & Terms</a></li>\r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /view/write.jsp(70,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("userID");
      // /view/write.jsp(70,1) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/view/write.jsp(70,1) 'null'",_jsp_getExpressionFactory().createValueExpression("null",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /view/write.jsp(71,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.userID}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t");
          if (_jspx_meth_c_005fset_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /view/write.jsp(72,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("userID");
      // /view/write.jsp(72,2) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/view/write.jsp(72,2) '${sessionScope.userID}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${sessionScope.userID}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }
}
